FORMAT: 1A
HOST: http://staging.api.dibzparking.com/

# Customer

Customer Resource

## Customer Collection [/customer]

### Customer Registration [POST]

You may register a new customer using this action.

+ Request (application/json)

        {
            "first_name" : "John",
            "last_name" : "Doe",
            "middle_name" : "Smith",
            "email" : "john.doe@gmail.com",
            "password" : "password",
            "password_confirmation" : "password",
            "refer_code" : "XjIs21J",
            "contact" : "09185413111",
            "facebook_id" : "xSkIpqL12kNl1AsEswndInwkNi..."
            "google_id" : "aiwnLIWNLSn12NASli12nAl..."
        }

+ Response 200 (application/json)

        {
            "status" : true,
            "code" : 200,
            "data" : {
            "email": "john.doe@gmail.com",
            "refer_code" : "A638yUS9nq",
            "access_level" : "customer",
            "id" : 1,
            "user_info" : {
                    "first_name": "John",
                    "last_name": "Doe",
                    "middle_name": "Smith",
                    "contact": "09185413111",
                    "users_id": 1,
                    "id": 1
                }
            }
        }