## Group Forgot Password

### Forgot password [POST /user/password/forgot]

You can use this action to submit a forgot password request.

+ `email` - (required, email)

+ Request (application/json)

        {
            "email" : "john.smith@gmail.com"
        }

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200
        }

### Forgot password [POST /user/password/reset/{reset_code}]

You can use this action to completely reset your password after receiving reset code in your email.

+ Parameters
    + reset_code (required)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200
        }
