## Group Payments and Redeeming points

### Redeem accumulated points [POST /user/rewards/redeem?api_token={api_token}]

You may use this action to redeem points collected of the user to convert into dibz points.

+ Paremeteres
    + api_token (required)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200
        }

### Pay thru Paypal [GET paypal/load_wallet?amount={amount}&api_token={api_token}]

You may use this action to redirect the user to the paypal payment when loading dibz points.

+ Parameters
    + api_token (required)
    + amount (required, numeric) - amount should be 10 - 3000.

### Get DragonPay Available Channels [GET dragonpay/available_channels?amount={amount}]

You may use this action to get list of channels available for specified amount.

+ Parameters
    + amount (required, numeric, decimal)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200,
            "data": [
                {
                    "procId": "BAYD",
                    "shortName": "Bayad Center",
                    "longName": "Bayad Center",
                    "logo": "~/images/bayadcenterlogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay at any <a href='http://www.bayadcenter.com/branchdirectory-list' target='_blank'>Bayad Center branch</a> nationwide.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 50,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BDO",
                    "shortName": "BDO",
                    "longName": "BDO Internet Banking",
                    "logo": "~/images/bdologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "1678005430|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": true,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your BDO Retail Internet Banking (RIB) account to make a payment. Read our <a href='http://www.dragonpay.ph/bdorib-how-to' target='_blank'>BDO RIB guide</a> for more details.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "06:00",
                    "endTime": "21:30",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BDOA",
                    "shortName": "BDO ATM",
                    "longName": "Banco de Oro ATM",
                    "logo": "~/images/bdologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "0332|DRAGONPAY|Biller",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 2,
                    "status": "A",
                    "remarks": "Pay at any BDO ATM nationwide. Payments are processed next day. <a href='http://www.dragonpay.ph/bdo-atm-how-to/' target='_blank'>Click here for details</a>. Payments are processed next day.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 200,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BDRX",
                    "shortName": "BDO OTC Ref",
                    "longName": "BDO Cash Deposit w/ Ref",
                    "logo": "~/images/bdologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "1670333890|Dragonpay Corporation|Peso Savings",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 2,
                    "status": "A",
                    "remarks": "Perform a Cash Deposit with Reference Number at any BDO branch. Payments are automatically processed after a few minutes. NOTE: A <b>P25 Service Fee</b> will be added. Choose a different bank if you do not agree to this fee.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 2000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BPI",
                    "shortName": "BPI",
                    "longName": "BPI ExpressOnline/Mobile (Fund Transfer)",
                    "logo": "~/images/bpilogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "0075352743|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": true,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your BPI ExpressOnline/Mobile (EOLM) Banking account to make a <b>Fund Transfer</b>. Choose this option <i>only if</i> you have previously registered Dragonpay for <b>3rd Party Fund Transfer</b> or enabled <b>Fund Transfer to Anyone</b>. A small random verification fee is added.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "04:00",
                    "endTime": "21:30",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": true,
                    "surcharge": 0
                },
                {
                    "procId": "BPIB",
                    "shortName": "BPI EOL",
                    "longName": "BPI ExpressOnline (Bills Payment)",
                    "logo": "~/images/bpilogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "0071071065|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": true,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your BPI ExpressOnline (EOL) Banking account to make a <a href='http://www.dragonpay.ph/bpi-eol-biller-how-to' target='_blank'>bills payment</a>. ExpressMobile Bills Payment is <b>NOT</b> supported. NOTE: A <b>P5.00 Service Fee</b> will be added.",
                    "dayOfWeek": "XXXXXX0",
                    "startTime": "04:30",
                    "endTime": "21:30",
                    "minAmount": 50,
                    "maxAmount": 2000000,
                    "mustRedirect": true,
                    "surcharge": 0
                },
                {
                    "procId": "BPXB",
                    "shortName": "BPI OTC Biller",
                    "longName": "BPI Bills Payment",
                    "logo": "~/images/bpilogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "0071071065|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 2,
                    "status": "A",
                    "remarks": "Pay cash over-the-counter at any BPI branch through Bills Payment. NOTE: A <b>P50 Service Fee</b> will be added. Choose a different bank if you do not agree to this fee.",
                    "dayOfWeek": "XXXXXX0",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "LBC",
                    "shortName": "LBC",
                    "longName": "LBC",
                    "logo": "~/images/lbclogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY|DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay at any <a href='http://www.lbcexpress.com/' target='_blank'>LBC outlet</a> nationwide (except those inside SM Malls) 7-days-a-week. LBC is now a Bayad Center.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 50,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "SMR",
                    "shortName": "SM Retail",
                    "longName": "SM Dept/Supermarket/Savemore Counter",
                    "logo": "~/images/smlogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY|DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay at any Payment Counter of SM Dept Store, SM Supermarket, Savemore nationwide 7-days-a-week. Payments are processed end of day.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 50,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "CEBP",
                    "shortName": "Cebuana PeraPal",
                    "longName": "Cebuana Lhuillier PeraPal",
                    "logo": "~/images/cebuana.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "M0003|PPM0003|d12@goNp9Y",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay via Cebuana PeraPal at any Cebuana Lhuillier branch nationwide.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 1500,
                    "mustRedirect": true,
                    "surcharge": 0
                },
                {
                    "procId": "DPAY",
                    "shortName": "Prepaid Credits",
                    "longName": "Dragonpay Prepaid Credits",
                    "logo": "~/images/dragonpaylogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use the Dragonpay Mobile App and pay using your prepaid credits in realtime and earn bonus loyalty points with your purchase. Learn more about <a href='http://www.dragonpay.ph/credits' target='_blank'>Dragonpay Credits</a>.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": true,
                    "surcharge": 0
                },
                {
                    "procId": "MBTC",
                    "shortName": "Metrobank",
                    "longName": "Metrobankdirect",
                    "logo": "~/images/metrodlogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "442-7-44201021-4|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": true,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your Metrobankdirect Online Banking account to make a payment.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "04:00",
                    "endTime": "21:30",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": true,
                    "surcharge": 0
                },
                {
                    "procId": "MBTX",
                    "shortName": "Metrobank OTC",
                    "longName": "Metrobank Cash/Check Payment",
                    "logo": "~/images/metrologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "442-7-44201021-4|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 2,
                    "status": "A",
                    "remarks": "Deposit your cash or on-us check payment over-the-counter at any Metrobank branch nationwide. Branches outside Metro Manila may charge handling fee.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 2000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "MLH",
                    "shortName": "M Lhuillier",
                    "longName": "M. Lhuillier",
                    "logo": "~/images/mlhlogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay at any M. Lhuillier outlet nationwide 7-days-a-week. A <a href='http://www.dragonpay.ph/mlhuillier-how-to/#servicefee' target='_blank'>service fee</a> will be charged by M. Lhuillier directly to you. Payments are processed next day.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 180,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "RDS",
                    "shortName": "Robinsons",
                    "longName": "Robinsons Dept Store",
                    "logo": "~/images/rdslogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay at <a href='http://www.robinsonsdepartmentstore.com.ph/store-locator' target='_blank'>Robinsons Dept Store Bills Payment Counter</a> 7-days-a-week up to 7pm. Payments are processed end of day.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 50,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "CBC",
                    "shortName": "Chinabank",
                    "longName": "Chinabank Online",
                    "logo": "~/images/cbclogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "1241280112|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": true,
                    "hasManualEnrollment": false,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your Chinabank Online Banking account to make a payment.",
                    "dayOfWeek": "0XXXXXX",
                    "startTime": "06:00",
                    "endTime": "21:00",
                    "minAmount": 1,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "LBPA",
                    "shortName": "Landbank ATM",
                    "longName": "Landbank ATM Online",
                    "logo": "~/images/lbplogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY|ePaymentPortal|Biller",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 1,
                    "status": "A",
                    "remarks": "Pay using your Landbank ATM account at the <a href='https://epaymentportal.landbank.com/' target='_blank'>Landbank ePaymentPortal</a>. Landbank charges a PHP10.00 service fee. Visit our <a href='http://www.dragonpay.ph/landbank-atm-how-to' target='_blank'>How-To page</a> for more details.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "03:00",
                    "endTime": "21:30",
                    "minAmount": 1,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "RCBC",
                    "shortName": "RCBC",
                    "longName": "RCBC Online Banking",
                    "logo": "~/images/rcbca1logo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "0284001141|RCB|Biller",
                    "hasTxnPwd": true,
                    "hasManualEnrollment": false,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your RCBC AccessOne Online Banking account to make a payment. NOTE: A <b>P5.00 Service Fee</b> will be added.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": true,
                    "surcharge": 0
                },
                {
                    "procId": "UBP",
                    "shortName": "Unionbank",
                    "longName": "Unionbank Internet Banking",
                    "logo": "~/images/ubplogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "G0467-7629|DRAGONPAY|Biller",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your Unionbank Online Banking or EON account to make a payment.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "23:00",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                }
            ]
        }

### Pay thru DragonPay [GET /dragonpay/load_wallet?amount={amount}&procid={procid}&api_token={api_token}]

You may use this action to redirect the user to the dragonpay payment when loading dibz points.

+ Parameters
    + api_token (required)
    + amount (required, numeric, decimal)
    + procid (required, string) - procid to pass e.x (BAYD, BDO)
