## Group Payments and Redeeming points

### Redeem accumulated points [POST /user/rewards/redeem?api_token={api_token}]

You may use this action to redeem points collected by the user to convert into dibz points.

+ Paremeteres
    + api_token (required)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200
        }

### Pay thru Paypal [GET /paypal/load_wallet?amount={amount}&api_token={api_token}]

You may use this action to redirect the user to the paypal payment when loading dibz points.

+ Parameters
    + api_token (required)
    + amount (required, numeric) - amount should be 10 - 3000.

### Get DragonPay Available Channels [GET /dragonpay/available_channels?amount={amount}]

You may use this action to get list of channels available for specified amount.

+ Parameters
    + amount (required, numeric)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200,
            "data": [
                {
                    "procId": "BAYD",
                    "shortName": "Bayad Center",
                    "longName": "Bayad Center",
                    "logo": "~/images/bayadcenterlogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "DRAGONPAY",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 4,
                    "status": "A",
                    "remarks": "Pay at any <a href='http://www.bayadcenter.com/branchdirectory-list' target='_blank'>Bayad Center branch</a> nationwide.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 50,
                    "maxAmount": 200000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BDO",
                    "shortName": "BDO",
                    "longName": "BDO Internet Banking",
                    "logo": "~/images/bdologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "1678005430|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": true,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your BDO Retail Internet Banking (RIB) account to make a payment. Read our <a href='http://www.dragonpay.ph/bdorib-how-to' target='_blank'>BDO RIB guide</a> for more details.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "06:00",
                    "endTime": "21:30",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BDOA",
                    "shortName": "BDO ATM",
                    "longName": "Banco de Oro ATM",
                    "logo": "~/images/bdologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "0332|DRAGONPAY|Biller",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 2,
                    "status": "A",
                    "remarks": "Pay at any BDO ATM nationwide. Payments are processed next day. <a href='http://www.dragonpay.ph/bdo-atm-how-to/' target='_blank'>Click here for details</a>. Payments are processed next day.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 200,
                    "maxAmount": 1000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BDRX",
                    "shortName": "BDO OTC Ref",
                    "longName": "BDO Cash Deposit w/ Ref",
                    "logo": "~/images/bdologo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": false,
                    "pwd": "",
                    "defaultBillerId": "1670333890|Dragonpay Corporation|Peso Savings",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": false,
                    "type": 2,
                    "status": "A",
                    "remarks": "Perform a Cash Deposit with Reference Number at any BDO branch. Payments are automatically processed after a few minutes. NOTE: A <b>P25 Service Fee</b> will be added. Choose a different bank if you do not agree to this fee.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "00:00",
                    "endTime": "00:00",
                    "minAmount": 1,
                    "maxAmount": 2000000,
                    "mustRedirect": false,
                    "surcharge": 0
                },
                {
                    "procId": "BPI",
                    "shortName": "BPI",
                    "longName": "BPI ExpressOnline/Mobile (Fund Transfer)",
                    "logo": "~/images/bpilogo.jpg",
                    "currencies": "PHP",
                    "url": "",
                    "realTime": true,
                    "pwd": "",
                    "defaultBillerId": "0075352743|Dragonpay Corporation|Peso Checking",
                    "hasTxnPwd": false,
                    "hasManualEnrollment": true,
                    "type": 1,
                    "status": "A",
                    "remarks": "Use your BPI ExpressOnline/Mobile (EOLM) Banking account to make a <b>Fund Transfer</b>. Choose this option <i>only if</i> you have previously registered Dragonpay for <b>3rd Party Fund Transfer</b> or enabled <b>Fund Transfer to Anyone</b>. A small random verification fee is added.",
                    "dayOfWeek": "XXXXXXX",
                    "startTime": "04:00",
                    "endTime": "21:30",
                    "minAmount": 1,
                    "maxAmount": 1000000,
                    "mustRedirect": true,
                    "surcharge": 0
                }
            ]
        }

### Pay thru DragonPay [GET /dragonpay/load_wallet?amount={amount}&procid={procid}&api_token={api_token}]

You may use this action to redirect the user to the dragonpay payment when loading dibz points.

+ Parameters
    + api_token (required)
    + amount (required, numeric, decimal)
    + procid (required, string) - procid to pass e.x (BAYD, BDO)
