## Group User

### Get self [GET /user/self?api_token={api_token}]

You may get details of user using this action.

+ Parameter
    + api_token (required, string)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200,
            "data": [
                {
                    "id": 1,
                    "company": null,
                    "email": "john.doe@gmail.com",
                    "refer_code": "g1otZDl3AS",
                    "active": "",
                    "logged_in": "no",
                    "access_level": "customer",
                    "verify_status": 1,
                    "property_type": "non-residential",
                    "users_id": null,
                    "garages_id": null,
                    "primary": {
                        "id": 1,
                        "extension": ".jpg",
                        "name": "65d26f300ea51692256e9c73deba617820170529180639000000vZfA6wniHIg1nkS3yVkzvZGylh3UMmUeXqs",
                        "primary": "yes",
                        "category": "",
                    },
                    "information": {
                        "id": 1,
                        "first_name": "John",
                        "last_name": "Doe",
                        "middle_name": "Smith",
                        "birth_date": "1994-11-14",
                        "contact": "09059770903",
                        "gender": "male",
                        "address": "2A-1 Suburban Villas Cainta Rizal"
                    },
                    "reward_points": {
                        "id": 1,
                        "amount": 0.00
                    },
                    "load_balance": {
                        "id": 2,
                        "load_balance": 200.00
                    }
                }
            ]
        }

### Get uploaded pictures of user [GET /user/{user_id}/picture?filter={filter}]

You may get the list of pictures of the user using this action

+ Parameter
    + user_id (required, numeric) - Customer Id
    + filter (optional) - Could be (all, valid_id...)

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200,
            "data": {
            "total": 5,
            "per_page": 15,
            "current_page": 1,
            "last_page": 1,
            "next_page_url": null,
            "prev_page_url": null,
            "from": 1,
            "to": 5,
            "data": [
                    {
                        "id": 1,
                        "extension": ".jpg",
                        "name": "92d27acd7ab4e6806a1ec1fdfa7cf2a73unirv5QieDHVsOkKNnP6UXkKUQc3xY50RCwwu4gHUTLh",
                        "primary": "no",
                        "category": "general"
                    },
                    {
                        "id": 2,
                        "extension": ".jpg",
                        "name": "3f94885fff8031a82e2d44dad1e2e397BZQkT8FJro5X5bdgJA2K2Y1zXFb8dSpGdehsSyG5ijJjh",
                        "primary": "no",
                        "category": "general"
                    },
                    {
                        "id": 3,
                        "extension": ".jpg",
                        "name": "9e2649f352004f098d5fe591e66dc17dLaQXNAF6B7OqL1yWRgbMNZPx8tWRi4uviUQTA4CvxsNKs",
                        "primary": "no",
                        "category": "general"
                    },
                    {
                        "id": 4,
                        "extension": ".jpg",
                        "name": "8cab112f9e634b1e47cdd8c704a5e210gsXAJ4QE9q19PqmYma0EH3QpeOx55Q2RkIqkh9b5m1nvk",
                        "primary": "no",
                        "category": "general"
                    },
                    {
                        "id": 5,
                        "extension": ".jpg",
                        "name": "65d26f300ea51692256e9c73deba617820170529180639000000vZfA6wniHIg1nkS3yVkzvZGylh3UMmUeXqs",
                        "primary": "yes",
                        "category": ""
                    }
                ]
            }
        }

### Upload pictures of user [POST /user/{user_id}/picture?api_token={api_token}]

You may use this action to upload images of the user.

+ `pictures[]` - (required, array) Image file object or base64 string.

+ Request (application/json)

        {
            "pictures[]" : "/9j/4AAQSkZJRgABAgAABAgAAAQABAAD/2wB..."
        }

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200,
            "data": [
                {
                    "extension": ".jpg",
                    "name": "5e11307f7d3a60a56f01956114390bbe20170609162357000000vBJLbEFya1f6XbI3mgt9jhAUHnIX3z6eKtO",
                    "category": "",
                    "id": 16
                }
            ]
        }

### Set picture primary [POST /user/{user_id}/picture/{picture_id}?api_token={api_token}]

You may use this action to set uploaded images of the user to primary or not.

+ `primary` - (required) Could be (yes or no).
+ `_method` - (required)

+ Request (application/json)

        {
            "primary" : "yes",
            "_method" : "PUT"
        }

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200,
            "data": [
                {
                    "extension": ".jpg",
                    "name": "5e11307f7d3a60a56f01956114390bbe20170609162357000000vBJLbEFya1f6XbI3mgt9jhAUHnIX3z6eKtO",
                    "category": "",
                    "id": 1
                }
            ]
        }

### Remove uploaded picture [POST /user/{user_id}/picture/{picture_id}?api_token={api_token}]

You may use this action to remove uploaded images of the user.

+ `_method` - (required)

+ Request (application/json)

        {
            "_method" : "DELETE"
        }

+ Response 200 (application/json)

        {
            "status": true,
            "code": 200
        }
